version: "3.9"

services:
  web:
    image: legend-flask-app
    ports:
      - "5000:5000"

  client:
    image: alpine
    command: sh -c "apk add --no-cache curl && curl http://web:5000"
    depends_on:
      - web

